version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hpost-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hpost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
