export const ApiResponseCode = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  DUPLICATE_ENTITY: 'DUPLICATE_ENTITY',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export type ApiResponseCodeEnum =
  (typeof ApiResponseCode)[keyof typeof ApiResponseCode];
